### PR TITLE
React Native 1-day training Barcelona Landing page (March 19th)

### PR DESCRIPTION
**Pull request by horacioh**

### CODE REVIEW

**Comment by flexbox** [comment]
I think there is a missing requirement here:
- Install all the stack __before__ the session

`NodeJs` and `Expo`?
or
`NodeJS`, `watchman` and `react-native-cli`

**Comment by horacioh** [comment]
hey David!
thanks for reviewing :)

is there a requirements section on the landing page? XD

I create this video to share with the students before the training: https://www.youtube.com/watch?v=WddC85CkR5g

maybe this helps!

**Comment by flexbox** [comment]
I think you can embed it for now and create another real section later :)

**Comment by horacioh** [comment]
but do you think is important to add the setup in the lnding page of the course before you pay?

I don’t think we have this to any of the courses. I would understand if this was a page for people that bought the course already but its not the case.

let me know what you think!

**Comment by flexbox** [comment]
@horacioh In fact maybe we can create a new repo
https://github.com/reactjsacademy/reactjsacademy/setup

An add all the instructions there like https://github.com/lewagon/setup/

**Pull request merged**
